name: gaussian_splatting
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=10.2
  - plyfile
  - python=3.7.13
  - pip=22.3.1
  - pytorch=1.9.0
  - torchaudio=0.9.0
  - torchvision=0.10.0
  - tqdm
  - pip:
    # - submodules/3dgs_diff_rasterizer_with_contribution
    - submodules/diff-gaussian-rasterization
